export default [{
  files: ["modal_gen/ui/assets/**/*.js"],
  languageOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
    globals: {
      document: "readonly",
      window: "readonly",
      location: "readonly",
      navigator: "readonly",
      fetch: "readonly",
      URL: "readonly",
      FormData: "readonly",
      Blob: "readonly",
      FileReader: "readonly",
      HTMLElement: "readonly",
      crypto: "readonly",
      setTimeout: "readonly",
      clearTimeout: "readonly",
      setInterval: "readonly",
      clearInterval: "readonly",
      requestAnimationFrame: "readonly",
      console: "readonly",
    },
  },
  rules: {
    "no-undef": "error",
    "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    "no-redeclare": "error",
    "no-global-assign": "error",
    "no-unreachable": "error",
    "no-constant-condition": ["error", { checkLoops: false }],
    eqeqeq: ["error", "always", { null: "ignore" }],
  },
}];
