CONTRACT = "modal-2d.generation.v2"
OPERATION = "modal-2d.image.text_to_image.v1"
MAX_BATCH_SIZE = 8
ARTIFACT_VOLUME = "modal-gen-artifacts"
LEGACY_ARTIFACT_VOLUME = "modal-2d-artifacts"
JOB_TRANSPORT = "modal.FunctionCall"
ARTIFACT_ROLE = "primary-image"
ARTIFACT_MIME = "image/png"
DEFAULT_MODEL = "sana-sprint-1.6b"
MAX_PROMPT_CHARS = 4000
MAX_SEED = 2**32 - 1
