PREFETCH_APP_NAME = "modal-2d-prefetch"
APP_NAME = PREFETCH_APP_NAME
PROVIDER = "modal-2d"
CONTRACT = "modal-2d.generation.v2"
CAPABILITY_KIND = "image.generate"
OPERATION = "modal-2d.image.text_to_image.v1"
PREFETCH_FUNCTION = "prefetch"
ARTIFACT_ROLE = "primary-image"
ARTIFACT_MIME = "image/png"
ARTIFACT_FORMAT = "png"
ARTIFACT_VOLUME = "modal-2d-artifacts"
MODELS_VOLUME = "modal-2d-models"
IMAGE_SIZE = 1024
MAX_PROMPT_CHARS = 4000
MAX_SEED = 2**32 - 1
MAX_BATCH_SIZE = 8
JOB_TRANSPORT = "modal.FunctionCall"
