"use strict";
const $=s=>document.querySelector(s);
const state={session:sessionStorage.getItem("modal2d.session")||"",connected:false,jobs:[],job:null,artifactIndex:0,blobUrl:null,poll:null};
const terminal=new Set(["succeeded","failed","cancelled","expired"]);
function toast(message,kind=""){const el=document.createElement("div");el.className=`toast ${kind}`;el.textContent=message;$("#toasts").append(el);setTimeout(()=>el.remove(),3500)}
function debug(method,path,status,data){$("#debug-log").textContent=`${method} ${path}\nHTTP ${status}\n\n${typeof data==="string"?data:JSON.stringify(data,null,2)}`}
async function request(path,options={}){
  const headers={...(options.headers||{})};if(state.session)headers["X-Modal-2D-Session"]=state.session;
  let body=options.body;if(body&&!(body instanceof FormData)){headers["Content-Type"]="application/json";body=JSON.stringify(body)}
  let res;try{res=await fetch(path,{...options,headers,body})}catch{setAgent("bad","Agent 不可达");throw new Error("无法连接本地 Agent")}
  const type=res.headers.get("content-type")||"";const data=type.includes("application/json")?await res.json():type.includes("image/")?await res.blob():await res.text();
  debug(options.method||"GET",path,res.status,data instanceof Blob?`Blob ${data.size} bytes`:data);
  if(!res.ok){const err=new Error(data&&data.detail?data.detail:`HTTP ${res.status}`);err.status=res.status;throw err}return{data,res};
}
function setAgent(mode,text){const el=$("#agent-status");el.dataset.state=mode;el.lastElementChild.textContent=text}
function openSettings(){$("#settings").classList.add("open");$("#settings").setAttribute("aria-hidden","false");$("#scrim").hidden=false}
function closeSettings(){$("#settings").classList.remove("open");$("#settings").setAttribute("aria-hidden","true");$("#scrim").hidden=true}
function setConnected(value){state.connected=value;setAgent(value?"ok":"warn",value?"Modal 已连接":"Modal 未连接");$("#form-message").textContent=value?"准备就绪，任务会直接提交到 Modal。":"请先在设置中输入 Modal Token。";$("#drawer-status").textContent=value?"已连接 Modal":"尚未连接"}
function parseTokenCommand(value){const id=value.match(/(?:^|\s)--token-id(?:=|\s+)(?:["']([^"']+)["']|(\S+))/i),secret=value.match(/(?:^|\s)--token-secret(?:=|\s+)(?:["']([^"']+)["']|(\S+))/i),hint=$("#parse-hint");if(!value.trim()){hint.className="parse-hint";hint.textContent="粘贴后自动提取 ID 和 Secret。";return false}if(!id||!secret){hint.className="parse-hint error";hint.textContent="未识别到完整的 --token-id 和 --token-secret。";return false}$("#token-id").value=id[1]||id[2];$("#token-secret").value=secret[1]||secret[2];hint.className="parse-hint ok";hint.textContent="已提取 Token ID 和 Secret，可以直接连接。";return true}
async function health(){try{const{data}=await request("/health");setConnected(Boolean(data.modal_connected))}catch{setAgent("bad","Agent 不可达")}}
async function connect(){const token_id=$("#token-id").value.trim(),token_secret=$("#token-secret").value.trim();state.session=$("#session-token").value.trim();sessionStorage.setItem("modal2d.session",state.session);if(!token_id||!token_secret){toast("请填写 Token ID 和 Secret","error");return}const btn=$("#connect");btn.disabled=true;try{await request("/modal/connect",{method:"POST",body:{token_id,token_secret}});setConnected(true);$("#token-secret").value="";await loadModels();closeSettings();toast("Modal 连接成功")}catch(e){$("#drawer-status").textContent=`连接失败：${e.message}`;toast(`连接失败：${e.message}`,"error")}finally{btn.disabled=false}}
async function disconnect(){try{await request("/modal/connect",{method:"DELETE"});setConnected(false);toast("已断开 Modal")}catch(e){toast(e.message,"error")}}
async function loadModels(){try{const{data}=await request("/v1/models");const models=Array.isArray(data.models)?data.models:[];if(models.length)$("#model").innerHTML=models.map(m=>`<option value="${esc(m.id)}">${esc(m.name||m.id)}</option>`).join("")}catch(e){if(e.status!==409)toast(`模型加载失败：${e.message}`,"error")}}
function parseSeeds(){const values=$("#seeds").value.split(/[\s,]+/).filter(Boolean).map(Number);if(!values.length||values.length>8||values.some(v=>!Number.isInteger(v)||v<0||v>4294967295)||new Set(values).size!==values.length)throw new Error("Seeds 需要 1–8 个不重复整数");return values}
function payload(){const prompt=$("#prompt").value.trim();if(!prompt)throw new Error("请先描述你想生成的画面");const body={prompt,model:$("#model").value};if($("#batch-toggle").checked)body.seeds=parseSeeds();else{const seed=Number($("#seed").value);if(!Number.isInteger(seed)||seed<0||seed>4294967295)throw new Error("Seed 不合法");body.seed=seed}const guidance=$("#guidance").value.trim();if(guidance){const n=Number(guidance);if(!Number.isFinite(n)||n<0||n>20)throw new Error("Guidance 需在 0–20 之间");body.guidance=n}return body}
async function generate(){if(!state.connected){openSettings();toast("请先连接 Modal","error");return}let body;try{body=payload()}catch(e){toast(e.message,"error");return}const btn=$("#generate");btn.disabled=true;showProgress("正在提交任务");try{const{data}=await request("/v1/jobs",{method:"POST",body});state.job=data;state.artifactIndex=0;$("#job-state").textContent=`${data.status} · ${data.id}`;await loadJobs();startPolling();toast("任务已提交")}catch(e){showEmpty();toast(`提交失败：${e.message}`,"error")}finally{btn.disabled=false}}
function showProgress(copy){$("#result-empty").hidden=true;$("#result-image").hidden=true;$("#result-progress").hidden=false;$("#progress-copy").textContent=copy}
function showEmpty(){$("#result-empty").hidden=false;$("#result-progress").hidden=true;$("#result-image").hidden=true}
async function poll(){if(!state.job)return;try{const{data}=await request(`/v1/jobs/${encodeURIComponent(state.job.id)}`);state.job=data;$("#job-state").textContent=`${data.status} · ${data.id}`;if(data.status==="succeeded"){stopPolling();await loadArtifact(0);await loadJobs()}else if(terminal.has(data.status)){stopPolling();showEmpty();toast(`任务结束：${data.status}`,"error")}else showProgress(data.status==="submitting"?"正在提交到 Modal":"GPU 正在生成，请稍候")}catch(e){stopPolling();toast(`轮询失败：${e.message}`,"error")}}
function startPolling(){stopPolling();poll();state.poll=setInterval(poll,1800)}function stopPolling(){if(state.poll)clearInterval(state.poll);state.poll=null}
function descriptors(){if(!state.job?.result)return[];if(Array.isArray(state.job.result.artifacts))return state.job.result.artifacts;return state.job.result.artifact?[state.job.result.artifact]:[]}
async function loadArtifact(index){const items=descriptors();if(!items.length)return;state.artifactIndex=index;const path=items.length>1?`/v1/jobs/${encodeURIComponent(state.job.id)}/artifacts/${index}`:`/v1/jobs/${encodeURIComponent(state.job.id)}/artifact`;showProgress("正在下载并校验图片");try{const{data,res}=await request(path);if(!(data instanceof Blob))throw new Error("产物不是图片");if(state.blobUrl)URL.revokeObjectURL(state.blobUrl);state.blobUrl=URL.createObjectURL(data);const img=$("#result-image");img.src=state.blobUrl;img.hidden=false;$("#result-progress").hidden=true;$("#result-empty").hidden=true;$("#download").disabled=false;const expected=items[index].sha256,actual=res.headers.get("x-artifact-sha256");$("#verify-state").textContent=expected&&actual&&expected.toLowerCase()===actual.toLowerCase()?`SHA-256 已验证 · ${actual.slice(0,10)}…`:"图片已加载";renderCandidates()}catch(e){showEmpty();toast(`产物读取失败：${e.message}`,"error")}}
function renderCandidates(){const items=descriptors();$("#candidate-tabs").innerHTML=items.length>1?items.map((_,i)=>`<button class="${i===state.artifactIndex?"active":""}" data-index="${i}">${i+1}</button>`).join(""):""}
async function loadJobs(){try{const{data}=await request("/v1/jobs?limit=12");state.jobs=Array.isArray(data.jobs)?data.jobs:[];renderJobs()}catch(e){toast(`任务加载失败：${e.message}`,"error")}}
function renderJobs(){const root=$("#job-list");if(!state.jobs.length){root.innerHTML='<div class="list-empty">还没有生成任务</div>';return}root.innerHTML=state.jobs.map(j=>`<article class="job-card" data-id="${esc(j.id)}"><strong>${esc(j.model||"生成任务")}</strong><b data-state="${esc(j.status)}">${esc(j.status)}</b><span>${esc(j.id)}</span><span>${formatTime(j.created_at)}</span></article>`).join("")}
async function selectJob(id){const row=state.jobs.find(j=>j.id===id);if(!row)return;state.job=row;$("#job-state").textContent=`${row.status} · ${row.id}`;if(row.status==="succeeded")await loadArtifact(0);else if(!terminal.has(row.status)){showProgress("GPU 正在生成，请稍候");startPolling()}else{showEmpty();toast(`任务状态：${row.status}`)}}
function download(){if(!state.blobUrl)return;const descriptor=descriptors()[state.artifactIndex];const a=document.createElement("a");a.href=state.blobUrl;a.download=`${descriptor?.id||"modal-2d"}.png`;a.click()}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function formatTime(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleString("zh-CN",{hour12:false})}
$("#open-settings").onclick=openSettings;$("#close-settings").onclick=closeSettings;$("#scrim").onclick=closeSettings;$("#connect").onclick=connect;$("#disconnect").onclick=disconnect;$("#generate").onclick=generate;$("#refresh-jobs").onclick=loadJobs;$("#download").onclick=download;
$("#prompt").oninput=e=>$("#prompt-count").textContent=`${e.target.value.length} / 4000`;
$("#token-command").addEventListener("input",e=>parseTokenCommand(e.target.value));
$("#token-command").addEventListener("paste",e=>setTimeout(()=>parseTokenCommand(e.target.value),0));
$("#batch-toggle").onchange=e=>{$("#batch-seeds-wrap").hidden=!e.target.checked;$("#seed-wrap").hidden=e.target.checked};
$("#candidate-tabs").onclick=e=>{const b=e.target.closest("button[data-index]");if(b)loadArtifact(Number(b.dataset.index))};
$("#job-list").onclick=e=>{const card=e.target.closest("[data-id]");if(card)selectJob(card.dataset.id)};
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter")generate();if(e.key==="Escape")closeSettings()});
$("#session-token").value=state.session;
health().then(()=>{loadJobs();if(state.connected)loadModels();else openSettings()});
